local SCENE_HELPER = require "main.gui.scene_helper"
local MONARCH = require "monarch.monarch"
local Box = require "main.objects.box"
local Dumbbell = require "main.objects.dumbbell"
local Sphere = require "main.objects.sphere"
local Capsule = require "main.objects.capsules"
local ConvexMesh = require "main.objects.convex_mesh"
local ConcaveMesh = require "main.objects.concave_mesh"

local SPHERE_RADIUS = 1.0
local NB_SPHERES = 20

local function create_physics(self)
	local settings = {
		gravity = vmath.vector3(0, -9.81, 0)
	}
	self.world = rp3d.createPhysicsWorld(settings)
	---@type GameBox[]
	self.objects = {}
	self.spheres = {}

	self.joints = {}

	-- Create all the spheres of the scene
	for i = 0, NB_SPHERES - 1 do
		local sphere = Sphere(true, SPHERE_RADIUS, self.world)
		sphere.collider:setMaterialBounciness(0)
		if (i == 0) then
			sphere.body:setType(rp3d.BodyType.STATIC)
		end
		table.insert(self.objects, sphere)
		table.insert(self.spheres, sphere)
	end

	local space = 0.5

	for i = 0, NB_SPHERES - 1 do
		local pos = vmath.vector3(i * (2 * SPHERE_RADIUS + space), 20, 0)
		self.spheres[i + 1].body:setTransformPosition(pos)
	end

	for i = 0, NB_SPHERES-2 do
		local body1 = self.spheres[i + 1].body
		local body2 = self.spheres[i + 2].body
		local body1Position = body1:getTransformPosition();
		local anchorPointWorldSpace = body1Position;
		local jointInfo = rp3d.createBallAndSocketJointInfoWorldSpace(body1, body2, anchorPointWorldSpace);
		jointInfo.isCollisionEnabled = false;
		local joint = self.world:createJoint(jointInfo)
	end


end

function init(self)
	create_physics(self)

	--msg.post("main:/camera3d", "set_position", { position = vmath.vector3(-8, 15, 100) })

	SCENE_HELPER.scene_new({
		name = "BallSocket Chain",
		world = self.world
	})
	--timer.delay(0.05,false,function()
	--	MONARCH.show(MONARCH.top(), { reload = true })
	--end)
end

function update(self, dt)
	SCENE_HELPER.update(dt)
	SCENE_HELPER.updatePhysics(dt, self.objects)
end

function final(self)
	for _, obj in ipairs(self.objects) do
		obj:dispose()
	end
	self.objects = nil

	rp3d.destroyPhysicsWorld(self.world)
	-- self.world:Destroy()
	SCENE_HELPER.scene_final()
end



